import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ProcessProvider } from "@/context/ProcessContext";
import { AuthProvider } from "@/context/AuthContext";

import { Toaster } from "@/components/ui/sonner";
import { Analytics } from "../_components/Analytics";
import Header from "../_components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vision Plus Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ProcessProvider>
            <Analytics />
            <Header  />
            {children}
            <Toaster />
          </ProcessProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
