import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ProcessProvider } from "@/context/ProcessContext";
import { AuthProvider } from "@/context/AuthContext";
import Header from "./_components/Header";
import { Analytics } from "./_components/Analytics";
import { Toaster } from "@/components/ui/sonner";
import { getCurrentUser } from "@/lib/auth-server";
import { db } from "@/lib/prisma";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vision Plus Management System",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();
  let userDetails = null;

  if (user?.id) {
    userDetails = await db.userDetails.findUnique({
      where: { userId: user.id },
    });
  }

  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ProcessProvider>
            <Analytics />
            <Header serverUser={user} initialExtraDetails={userDetails} />
            {children}
            <Toaster />
          </ProcessProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
